### ISSUE TITLE
Fabric is causing a crash in Debug builds

### ISSUE THREAD

**Issue by krisorr** [Shopify/mobile-buy-sdk-android#136]

**Comment by krisorr** [comment]
pl: Cancelling event due to no window focus: MotionEvent { action=ACTION_CANCEL, actionButton=0, id[0]=0, x[0]=794.70703, y[0]=1397.6367, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=130723420, downTime=130720452, deviceId=0, source=0x1002 }
05-16 12:42:10.535 29827-29827/com.greats.mobileapp W/ViewRootImpl: Cancelling event due to no window focus: MotionEvent { action=ACTION_CANCEL, actionButton=0, id[0]=0, x[0]=794.70703, y[0]=1397.6367, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=130723420, downTime=130720452, deviceId=0, source=0x1002 }
05-16 12:42:10.535 29827-29827/com.greats.mobileapp W/ViewRootImpl: Cancelling event due to no window focus: MotionEvent { action=ACTION_CANCEL, actionButton=0, id[0]=0, x[0]=794.70703, y[0]=1397.6367, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=130723420, downTime=130720452, deviceId=0, source=0x1002 }
05-16 12:43:09.263 29827-29827/com.greats.mobileapp E/FabricHelper: Img error https://cdn.shopify.com/s/files/1/0238/2821/products/Pronto-Nero-Product-01.jpg (67KB)

05-16 12:43:09.275 29827-29827/com.greats.mobileapp D/AndroidRuntime: Shutting down VM
05-16 12:43:09.275 29827-29827/com.greats.mobileapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.greats.mobileapp, PID: 29827
                                                                     java.lang.IllegalStateException: Must Initialize Fabric before using singleton()
                                                                         at io.fabric.sdk.android.Fabric.singleton(Fabric.java:273)
                                                                         at io.fabric.sdk.android.Fabric.getKit(Fabric.java:524)
                                                                         at com.crashlytics.android.answers.Answers.getInstance(Answers.java:32)
                                                                         at com.shopify.merchantapp.util.FabricHelper.logGeneralErrorEvent(FabricHelper.java:59)
                                                                         at com.shopify.merchantapp.ui.common.FixedAspectImageView$1.onError(FixedAspectImageView.java:129)
                                                                         at com.squareup.picasso.ImageViewAction.error(ImageViewAction.java:67)
                                                                         at com.squareup.picasso.Picasso.deliverAction(Picasso.java:563)
                                                                         at com.squareup.picasso.Picasso.complete(Picasso.java:510)
                                                                         at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:117)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by krisorr** [comment]
This happens when the network in not working correctly, and Picasso times out.
Not urgent to fix, will only happen on debug builds.
