### ISSUE TITLE
Erro open app with apoloDebug sample

### ISSUE THREAD

**Issue by fernandodeveloper** [Shopify/mobile-buy-sdk-android#442]
Compile normal, and when open the app show ("Mobile sample app problem, error") (android error dialog)

and the log mensagem is this

stracktrace

`FATAL EXCEPTION: main
                                                 Process: com.shopify.sample, PID: 2869
                                                 android.view.InflateException: Binary XML file line #13: Error inflating class TextView
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:719)
                                                     at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
                                                     at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
                                                     at android.support.v7.view.menu.MenuItemImpl.setActionView(MenuItemImpl.java:624)
                                                     at android.support.v7.view.menu.MenuItemImpl.setActionView(MenuItemImpl.java:43)
                                                     at android.support.v4.view.MenuItemCompat.setActionView(MenuItemCompat.java:310)
                                                     at android.support.v7.view.SupportMenuInflater$MenuState.setItem(SupportMenuInflater.java:469)
                                                     at android.support.v7.view.SupportMenuInflater$MenuState.addItem(SupportMenuInflater.java:483)
                                                     at android.support.v7.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:200)
                                                     at android.support.v7.view.SupportMenuInflater.inflate(SupportMenuInflater.java:122)
                                                     at com.shopify.sample.view.collections.CollectionListActivity.onCreateOptionsMenu(CollectionListActivity.java:60)
                                                     at android.app.Activity.onCreatePanelMenu(Activity.java:2646)
                                                     at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:362)
                                                     at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:98)
                                                     at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:335)
                                                     at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:98)
                                                     at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:454)
                                                     at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:146)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5598)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: android.content.res.Resources$NotFoundException: File res/drawable/count_badge.xml from drawable resource ID #0x7f02006b
                                                     at android.content.res.Resources.loadDrawable(Resources.java:3446)
                                                     at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                                                     at android.view.View.<init>(View.java:3694)
                                                     at android.widget.TextView.<init>(TextView.java:916)
                                                     at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)`

**Comment by henrytao-me** [comment]
Have you tried clean build and disable instant run?
