### ISSUE TITLE
 java.lang.NoSuchMethodError: No static method com_shopify_buy3_Storefront$ShopQuery$$Lambda$3_lambda$collections$2(Lcom/shopify/buy3/Storefront$ShopQuery$CollectionsArguments;)V in class Lcom/shopify/buy3/Storefront$ShopQuery; or its super classes (declaration of 'com.shopify.buy3.Storefront$ShopQuery' appears in /data/app/com.palamsari.main-1/base.apk)                                                        at com.shopify.buy3.Storefront$ShopQuery$$Lambda$3.define(Unknown Source)                                                        at com.shopify.buy3.Storefront$ShopQuery.collections(Storefront.java:22738)

### ISSUE THREAD

**Issue by KavithaAnandan** [Shopify/mobile-buy-sdk-android#453]
Can someone  please help me on this.Am getting this error once i added retro lambda.
and for one day fully i tried i couldnt resolve this issue.

**Comment by henrytao-me** [comment]
Sorry. I have to edit the title to make it shorter. Have you tried clean build? What version are you using? `3.0.7`?

**Comment by sav007** [comment]
I guess this is the same issue https://github.com/Shopify/mobile-buy-sdk-android/issues/437
