### ISSUE TITLE
Issue on checkout debug apk (com.shopify.mobilebuysdk:buy:2.1.0) related to Date

### ISSUE THREAD

**Issue by prashant0611** [Shopify/mobile-buy-sdk-android#489]
Issue on Checkout code its giving error. But at same point and same code earlier release version are working fine.
Code: 
```java
return new Callback<Checkout>() {
            @Override
            public void success(Checkout checkout) {
                Log.d("ShopifyAppApplication", "Success Inside wrapCheckoutCallback");
                ShopifyAppApplication.this.checkout = checkout;
                callback.success(checkout);
            }

            @Override
            public void failure(BuyClientError error) {
                Log.d("ShopifyAppApplication", "Fail Inside wrapCheckoutCallback");
                callback.failure(error);
            }
        };
```
Error:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
                                                                                         at java.util.Calendar.setTime(Calendar.java:1089)
                                                                                         at java.text.SimpleDateFormat.format(SimpleDateFormat.java:953)
                                                                                         at java.text.SimpleDateFormat.format(SimpleDateFormat.java:946)
                                                                                         at java.text.DateFormat.format(DateFormat.java:337)
                                                                                         at com.google.gson.DefaultDateTypeAdapter.write(DefaultDateTypeAdapter.java:88)
                                                                                         at com.google.gson.DefaultDateTypeAdapter.write(DefaultDateTypeAdapter.java:40)
                                                                                         at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:74)
                                                                                         at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
                                                                                         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
                                                                                         at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
                                                                                         at com.google.gson.Gson.toJson(Gson.java:669)
                                                                                         at com.google.gson.Gson.toJsonTree(Gson.java:562)
                                                                                         at com.google.gson.Gson.toJsonTree(Gson.java:541)
                                                                                         at com.shopify.buy.model.Checkout$CheckoutSerializer.serialize(Checkout.java:670)
                                                                                         at com.shopify.buy.model.Checkout$CheckoutSerializer.serialize(Checkout.java:664)
                                                                                         at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
                                                                                         at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:74)
                                                                                         at com.google.gson.Gson.toJson(Gson.java:669)
                                                                                         at com.google.gson.Gson.toJson(Gson.java:648)
                                                                                         at com.google.gson.Gson.toJson(Gson.java:603)
                                                                                         at com.google.gson.Gson.toJson(Gson.java:583)
                                                                                         at com.shopify.buy.model.ShopifyObject.toJsonString(ShopifyObject.java:62)
                                                                                         at com.shopify.buy.model.Checkout.copy(Checkout.java:596)
                                                                                         at com.shopify.buy.dataprovider.CheckoutServiceDefault.createCheckout(CheckoutServiceDefault.java:100)
                                                                                         at com.shopify.buy.dataprovider.CheckoutServiceDefault.createCheckout(CheckoutServiceDefault.java:91)
                                                                                         at com.shopify.buy.dataprovider.BuyClientDefault.createCheckout(BuyClientDefault.java:191)
                                                                                         at com.xyz.shopifytrial.application.ShopifyAppApplication.createCheckout(ShopifyAppApplication.java:646)
                                                                                         at com.xyz.shopifytrial.cartwish.CartActivity.createCheckout(CartActivity.java:210)
```

**Comment by sav007** [comment]
We no longer support SDK 2.0. Please migrate to new 3.x SDK.
