### ISSUE TITLE
java.io.IOException: Resource not found

### ISSUE THREAD

**Issue by aShaforostov** [Shopify/mobile-buy-sdk-android#503]
Hello) In my console I see this information

```
W/System.err: java.io.IOException: Resource not found: "org/joda/time/tz/data/ZoneInfoMap" ClassLoader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/devit_team.imobileframework-2/base.apk", zip file "/data/app/devit_team.imobileframework-2/split_lib_dependencies_apk.apk", zip file "/data/app/devit_team.imobileframework-2/split_lib_slice_0_apk.apk", zip file "/data/app/devit_team.imobileframework-2/split_lib_slice_1_apk.apk", zip file "/data/app/devit_team.imobileframework-2/split_lib_slice_2_apk.apk", zip file "/data/app/devit_team.imobileframework-2/split_lib_slice_3_apk.apk", zip file "/data/app/devit_team.imobileframework-2/split_lib_slice_4_apk.apk", zip file "/data/app/devit_team.imobileframework-2/split_lib_slice_5_apk.apk", zip file "/data/app/devit_team.imobileframework-2/split_lib_slice_6_apk.apk", zip file "/data/app/devit_team.imobileframework-2/split_lib_slice_7_apk.apk", zip file "/data/app/devit_team.imobileframework-2/split_lib_slice_8_apk.apk", zip file "/data/app/devit_team.imobileframework-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/devit_team.imobileframework-2/lib/arm, /data/app/devit_team.imobileframework-2/base.apk!/lib/armeabi-v7a, /data/app/devit_team.imobileframework-2/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/devit_team.imobileframework-2/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/devit_team.imobileframework-2/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/devit_team.imobileframework-2/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/devit_team.imobileframework-2/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/devit_team.imobileframework-2/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/devit_team.imobileframework-2/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/devit_team.imobileframework-2/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/devit_team.imobileframework-2/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/devit_team.imobileframework-2/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/devit_team.imobileframework-2/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]]
W/System.err:     at org.joda.time.tz.ZoneInfoProvider.openResource(ZoneInfoProvider.java:216)
W/System.err:     at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:129)
W/System.err:     at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:88)
W/System.err:     at org.joda.time.DateTimeZone.getDefaultProvider(DateTimeZone.java:532)
W/System.err:     at org.joda.time.DateTimeZone.getProvider(DateTimeZone.java:431)
W/System.err:     at org.joda.time.DateTimeZone.forTimeZone(DateTimeZone.java:349)
W/System.err:     at org.joda.time.DateTimeZone.getDefault(DateTimeZone.java:157)
W/System.err:     at org.joda.time.chrono.ISOChronology.getInstance(ISOChronology.java:79)
W/System.err:     at org.joda.time.DateTimeUtils.getChronology(DateTimeUtils.java:269)
W/System.err:     at org.joda.time.format.DateTimeFormatter.selectChronology(DateTimeFormatter.java:1014)
W/System.err:     at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:923)
W/System.err:     at org.joda.time.DateTime.parse(DateTime.java:160)
W/System.err:     at com.shopify.buy3.Utils.parseDateTime(Utils.java:38)
W/System.err:     at com.shopify.buy3.Storefront$CustomerAccessToken.<init>(Storefront.java:13538)
W/System.err:     at com.shopify.buy3.Storefront$CustomerAccessTokenCreatePayload.<init>(Storefront.java:13690)
W/System.err:     at com.shopify.buy3.Storefront$Mutation.<init>(Storefront.java:18181)
W/System.err:     at com.shopify.buy3.RealMutationGraphCall.lambda$new$0(RealMutationGraphCall.java:40)
W/System.err:     at com.shopify.buy3.RealMutationGraphCall$$Lambda$1.convert(Unknown Source)
W/System.err:     at com.shopify.buy3.HttpResponseParser.parse(HttpResponseParser.java:50)
W/System.err:     at com.shopify.buy3.HttpCallbackWithRetry.onResponse(HttpCallbackWithRetry.java:71)
W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
```

I think this can cause a problem when I start using methods that use parseDateTime in Utils.java

**Comment by sav007** [comment]
Probably, do you have in project JodaTime dependency ?

**Comment by aShaforostov** [comment]
In my project I do not use JodaTime dependency. After doing a search, I found that the dependency is used only in the library Mobile Buy Sdk

**Comment by sav007** [comment]
That odd, we were pretty sure that it's transient dependency. We will investigate this issue.
Meantime could you pls add jodatime as dependency to your project: `net.danlew:android.joda:2.9.9`

**Comment by aShaforostov** [comment]
Thank you, problem solved

**Comment by Midhilaj** [comment]
not solved 
java.io.IOException: Resource not found: "org/joda/time/tz/data/ZoneInfoMap" ClassLoader: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.shopify.sample-1/base.apk", zip file "/data/app/com.shopify.sample-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.shopify.sample-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.shopify.sample-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.shopify.sample-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.shopify.sample-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.shopify.sample-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.shopify.sample-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.shopify.sample-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.shopify.sample-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.shopify.sample-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.shopify.sample-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.shopify.sample-1/lib/x86_64, /data/app/com.shopify.sample-1/base.apk!/lib/x86_64, /data/app/com.shopify.sample-1/split_lib_dependencies_apk.apk!/lib/x86_64, /data/app/com.shopify.sample-1/split_lib_slice_0_apk.apk!/lib/x86_64, /data/app/com.shopify.sample-1/split_lib_slice_1_apk.apk!/lib/x86_64, /data/app/com.shopify.sample-1/split_lib_slice_2_apk.apk!/lib/x86_64, /data/app/com.shopify.sample-1/split_lib_slice_3_apk.apk!/lib/x86_64, /data/app/com.shopify.sample-1/split_lib_slice_4_apk.apk!/lib/x86_64, /data/app/com.shopify.sample-1/split_lib_slice_5_apk.apk!/lib/x86_64, /data/app/com.shopify.sample-1/split_lib_slice_6_apk.apk!/lib/x86_64, /data/app/com.shopify.sample-1/split_lib_slice_7_apk.apk!/lib/x86_64, /data/app/com.shopify.sample-1/split_lib_slice_8_apk.apk!/lib/x86_64, /data/app/com.shopify.sample-1/split_lib_slice_9_apk.apk!/lib/x86_64, /system/lib64, /vendor/lib64]]]
12-19 10:28:37.833 13999-14250/com.shopify.sample W/System.err:     at org.joda.time.tz.ZoneInfoProvider.openResource(ZoneInfoProvider.java:216)
12-19 10:28:37.833 13999-14250/com.shopify.sample W/System.err:     at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:129)
12-19 10:28:37.833 13999-14250/com.shopify.sample W/System.err:     at org.joda.time.tz.ZoneInfoProvider.<init>(ZoneInfoProvider.java:88)
12-19 10:28:37.833 13999-14250/com.shopify.sample W/System.err:     at org.joda.time.DateTimeZone.getDefaultProvider(DateTimeZone.java:532)
12-19 10:28:37.833 13999-14250/com.shopify.sample W/System.err:     at org.joda.time.DateTimeZone.getProvider(DateTimeZone.java:431)
12-19 10:28:37.833 13999-14250/com.shopify.sample W/System.err:     at org.joda.time.DateTimeZone.forTimeZone(DateTimeZone.java:349)
12-19 10:28:37.833 13999-14250/com.shopify.sample W/System.err:     at org.joda.time.DateTimeZone.getDefault(DateTimeZone.java:157)
12-19 10:28:37.833 13999-14250/com.shopify.sample W/System.err:     at org.joda.time.chrono.ISOChronology.getInstance(ISOChronology.java:79)
12-19 10:28:37.833 13999-14250/com.shopify.sample W/System.err:     at org.joda.time.DateTimeUtils.getChronology(DateTimeUtils.java:269)
12-19 10:28:37.833 13999-14250/com.shopify.sample W/System.err:     at org.joda.time.format.DateTimeFormatter.selectChronology(DateTimeFormatter.java:1014)
12-19 10:28:37.833 13999-14250/com.shopify.sample W/System.err:     at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:923)
12-19 10:28:37.833 13999-14250/com.shopify.sample W/System.err:     at org.joda.time.DateTime.parse(DateTime.java:160)
12-19 10:28:37.833 13999-14250/com.shopify.sample W/System.err:     at com.shopify.buy3.Utils.parseDateTime(Utils.java:38)
12-19 10:28:37.834 13999-14250/com.shopify.sample W/System.err:     at com.shopify.buy3.Storefront$Product.<init>(Storefront.java:21615)
12-19 10:28:37.834 13999-14250/com.shopify.sample W/System.err:     at com.shopify.buy3.Storefront$ProductEdge.<init>(Storefront.java:22216)
12-19 10:28:37.834 13999-14250/com.shopify.sample W/System.err:     at com.shopify.buy3.Storefront$ProductConnection.<init>(Storefront.java:22102)
12-19 10:28:37.834 13999-14250/com.shopify.sample W/System.err:     at com.shopify.buy3.Storefront$Collection.<init>(Storefront.java:6491)
12-19 10:28:37.834 13999-14250/com.shopify.sample W/System.err:     at com.shopify.buy3.Storefront$CollectionEdge.<init>(Storefront.java:6813)
12-19 10:28:37.834 13999-14250/com.shopify.sample W/System.err:     at com.shopify.buy3.Storefront$CollectionConnection.<init>(Storefront.java:6699)
12-19 10:28:37.834 13999-14250/com.shopify.sample W/System.err:     at com.shopify.buy3.Storefront$Shop.<init>(Storefront.java:24511)
12-19 10:28:37.834 13999-14250/com.shopify.sample W/System.err:     at com.shopify.buy3.Storefront$QueryRoot.<init>(Storefront.java:23520)
12-19 10:28:37.834 13999-14250/com.shopify.sample W/System.err:     at com.shopify.buy3.RealQueryGraphCall.lambda$new$0(RealQueryGraphCall.java:42)
12-19 10:28:37.834 13999-14250/com.shopify.sample W/System.err:     at com.shopify.buy3.RealQueryGraphCall$$Lambda$1.convert(Unknown Source)
12-19 10:28:37.834 13999-14250/com.shopify.sample W/System.err:     at com.shopify.buy3.HttpResponseParser.parse(HttpResponseParser.java:50)
12-19 10:28:37.834 13999-14250/com.shopify.sample W/System.err:     at com.shopify.buy3.HttpCallbackWithRetry.onResponse(HttpCallbackWithRetry.java:71)
12-19 10:28:37.834 13999-14250/com.shopify.sample W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
12-19 10:28:37.834 13999-14250/com.shopify.sample W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
12-19 10:28:37.834 13999-14250/com.shopify.sample W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-19 10:28:37.834 13999-14250/com.shopify.sample W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-19 10:28:37.834 13999-14250/com.shopify.sample W/System.err:     at java.lang.Thread.run(Thread.java:761)
12

**Comment by sav007** [comment]
Closing due to inactivity.
