### ISSUE TITLE
GraphParseError during create Customer, Login

### ISSUE THREAD

**Issue by olegVovkZazmic** [Shopify/mobile-buy-sdk-android#520]
I faced this issue
I make request and have response 
`{"data":{"customerAccessTokenCreate":{"customerAccessToken":{"accessToken":"3aae3dcd088247fa09a6a6c3dfd10f0c","expiresAt":"2018-02-20T15:31:01Z"},"userErrors":[]}}}`

And after that I catch
`HttpResponseParser: failed to parse GraphQL response
                                                                                java.lang.ClassCastException: com.google.gson.JsonNull cannot be cast to com.google.gson.JsonObject
                                                                                    at com.shopify.buy3.HttpResponseParser.parseTopLevelResponse(HttpResponseParser.java:72)
                                                                                    at com.shopify.buy3.HttpResponseParser.parse(HttpResponseParser.java:48)
                                                                                    at com.shopify.buy3.HttpCallbackWithRetry.onResponse(HttpCallbackWithRetry.java:71)
                                                                                    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
                                                                                    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                    at java.lang.Thread.run(Thread.java:818)`

Please help!

**Comment by aShaforostov** [comment]
It's a bug of library. I'm found temporary solution
https://github.com/Shopify/mobile-buy-sdk-android/issues/502

**Comment by Sar777** [comment]
I confirm issue, but i have same error with my OkHttp client. I get list of collections:
```
java.lang.ClassCastException: com.google.gson.JsonNull cannot be cast to com.google.gson.JsonObject
                                                                         at com.shopify.buy3.HttpResponseParser.parseTopLevelResponse(HttpResponseParser.java:72)
                                                                         at com.shopify.buy3.HttpResponseParser.parse(HttpResponseParser.java:48)
                                                                         at com.shopify.buy3.RealGraphCall.execute(RealGraphCall.java:131)
                                                                         at com.common.RxUtil.lambda$rxGraphQueryCall$0$RxUtil(RxUtil.java:24)
                                                                         at com.common.RxUtil$$Lambda$0.subscribe(Unknown Source)
                                                                         at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
                                                                         at io.reactivex.Single.subscribe(Single.java:2801)
                                                                         at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
                                                                         at io.reactivex.Single.subscribe(Single.java:2801)
                                                                         at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                                                                         at io.reactivex.Single.subscribe(Single.java:2801)
                                                                         at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                                                                         at io.reactivex.Single.subscribe(Single.java:2801)
                                                                         at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                                                                         at io.reactivex.Single.subscribe(Single.java:2801)
                                                                         at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                                                                         at io.reactivex.Single.subscribe(Single.java:2801)
                                                                         at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
                                                                         at io.reactivex.Single.subscribe(Single.java:2801)
                                                                         at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
                                                                         at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                                                                         at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
                                                                         at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                         at java.lang.Thread.run(Thread.java:760)
```

**Comment by olegVovkZazmic** [comment]
@Sar777 show me your okHttp client which you created for graphClient

**Comment by Sar777** [comment]
Hi @olegVovkZazmic 

  ```
  @Singleton
    @Provides
    @NonNull
    OkHttpClient provideOkHttpClient(@NonNull Cache cache,
                                     @OkHttpInterceptors @NonNull List<Interceptor> interceptors,
                                     @OkHttpNetworkInterceptors @NonNull List<Interceptor> networkInterceptors) {
        final OkHttpClient.Builder okHttpBuilder = new OkHttpClient.Builder();
        for (Interceptor interceptor : interceptors) {
            okHttpBuilder.addInterceptor(interceptor);
        }

        for (Interceptor networkInterceptor : networkInterceptors) {
            okHttpBuilder.addNetworkInterceptor(networkInterceptor);
        }

        return okHttpBuilder
                .connectTimeout(5, TimeUnit.SECONDS) // Default 10 secs
                .writeTimeout(20, TimeUnit.SECONDS) // Default 10 secs
                .readTimeout(20, TimeUnit.SECONDS) // Default 10 secs
                .cache(cache)
                .build();
    }

    @Singleton
    @Provides
    @NonNull
    GraphClient provideGraphClient(@NonNull Context context,
                                @Named(SHOP_DOMAIN) @NonNull String shopDomain,
                                @Named(STOREFRONT_ACCESS_TOKEN) @NonNull String storeFrontAccessToken,
                                @NonNull OkHttpClient okHttpClient) {

        return GraphClient.builder(context)
                .shopDomain(shopDomain)
                .accessToken(storeFrontAccessToken)
                .httpClient(okHttpClient)
                .defaultHttpCachePolicy(HttpCachePolicy.CACHE_FIRST.expireAfter(1, TimeUnit.MINUTES))
                .build();
    }
```
OkHttp 3.9.1

**Comment by olegVovkZazmic** [comment]
Add this OkHttp for graph and try make request
for Module
` @Provides
    @Singleton
    OkHttpClient provideHttpClient() {
        OkHttpClient.Builder httpClient = new OkHttpClient.Builder();
        httpClient.addNetworkInterceptor(new HttpLoggingInterceptor().setLevel(BuildConfig.OKHTTP_LOG_LEVEL));
        return httpClient.build();
    }`

In build.gradle app 

`buildTypes {
        all {
            buildConfigField 'okhttp3.logging.HttpLoggingInterceptor.Level', 'OKHTTP_LOG_LEVEL', 'okhttp3.logging.HttpLoggingInterceptor.Level.BODY'`

and try make your request
