### ISSUE TITLE
Failed to parse GraphQL http response

### ISSUE THREAD

**Issue by khalilcodecorner** [Shopify/mobile-buy-sdk-android#598]
com.shopify.buy3.GraphParseError: Failed to parse GraphQL http response
        at com.shopify.buy3.HttpResponseParser.parseTopLevelResponse(HttpResponseParser.java:76)
        at com.shopify.buy3.HttpResponseParser.parse(HttpResponseParser.java:48)
        at com.shopify.buy3.HttpCallbackWithRetry.onResponse(HttpCallbackWithRetry.java:71)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.ClassCastException: com.google.gson.JsonNull cannot be cast to com.google.gson.JsonObject
        at com.shopify.buy3.HttpResponseParser.parseTopLevelResponse(HttpResponseParser.java:72)
        at com.shopify.buy3.HttpResponseParser.parse(HttpResponseParser.java:48) 
        at com.shopify.buy3.HttpCallbackWithRetry.onResponse(HttpCallbackWithRetry.java:71) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by khalilcodecorner** [comment]
i found out that cache is creating problem in this when i comment out the cache and set cache policy to  HttpCachePolicy.NETWORK_FIRST then it start working but when i include cache in it is cause problem again and show cache Key miss
