### ISSUE TITLE
BaseApplication: Failed to fetch shop settings

### ISSUE THREAD

**Issue by vijayxd** [Shopify/mobile-buy-sdk-android#613]
after build successful when i open app
im getting this error

2019-07-24 16:26:19.618 4846-4846/com.shopify.sample E/BaseApplication: Failed to fetch shop settings
    com.shopify.buy3.GraphError$HttpError: HTTP(403) 
        at com.shopify.buy3.internal.HttpResponseParser.successResponse(HttpResponseParser.kt:55)
        at com.shopify.buy3.internal.HttpResponseParser.parse(HttpResponseParser.kt:42)
        at com.shopify.buy3.internal.GraphHttpResultCallback.parse(RealGraphCall.kt:332)
        at com.shopify.buy3.internal.GraphHttpResultCallback.onResponse(RealGraphCall.kt:311)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)

**Comment by devsideal** [comment]
@vijayxd  Were you able to fix this issue?
