### ISSUE TITLE
Shopify will crash with okhttp 4.9.0

### ISSUE THREAD

**Issue by keepmovingljzy** [Shopify/mobile-buy-sdk-android#690]
Shopify will crash with okhttp 4.9.0

when I use the shopify with okhttp 4.9.0,it will crash,I have forced all versions to be unified
```
    configurations.all {
      resolutionStrategy.force 'com.squareup.okhttp3:okhttp:4.9.0'
      resolutionStrategy.force 'com.squareup.okhttp3:logging-interceptor:4.9.0'
    }
```
it will crash when run this code
```
        try {
            JodaTimeAndroid.init(context)

            val httpClient = OkHttpClient.Builder()
                .addNetworkInterceptor(HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY))
                .build()
            client = GraphClient.build(
                context,
                BuildConfig.SHOPIFY_SHOP_DOMAIN,
                BuildConfig.SHOPIFY_API_KEY
            ) {
                this.httpClient = httpClient
                this.httpCache(File(context.cacheDir, "/http")) {
                    this.cacheMaxSizeBytes = 1024 * 1024 * 10
                    this.defaultCachePolicy =
                        HttpCachePolicy.Default.CACHE_FIRST.expireAfter(20, TimeUnit.MINUTES)
                }
            }
        } catch (t: Throwable) {
            t.printStackTrace()
        }
```

The exception is java.lang.NoSuchMethodError: No static method create(Lokhttp3/internal/io/FileSystem;Ljava/io/File;IIJ)Lokhttp3/internal/cache/DiskLruCache; in class Lokhttp3/internal/cache/DiskLruCache; or its super classes (declaration of 'okhttp3.internal.cache.DiskLruCache' appears in /data/app/com.xxx.xxx-LJaR5pwAQuLp9OygATCHIg==/base.apk!classes3.dex)

how to deal with it?

**Comment by keepmovingljzy** [comment]
it will ok when I use okhttp 3.12.0

**Comment by PiotrWpl** [comment]
Hi,

the issue here is that `DiskLruCache` is an internal class that shouldn't be used by the Shopify SDK, and it seems that API for it has changed in okhttp 4.0+
Shopify team should stop using it, or update to support new API.

But as a workaround, You can either write your own implementation of the cache by extending `ResponseCacheStore` class or disable the cache, by removing:
```
this.httpCache(File(context.cacheDir, "/http")) {
                    this.cacheMaxSizeBytes = 1024 * 1024 * 10
                    this.defaultCachePolicy =
                        HttpCachePolicy.Default.CACHE_FIRST.expireAfter(20, TimeUnit.MINUTES)
                }
```

**Comment by keepmovingljzy** [comment]
thank you very much!

**Comment by TimoPtr** [comment]
It seems like the only solutions are:
1. wait for Shopify to fix this
2. don't use cache

**Comment by Faves** [comment]
Any update about this ?


Because of some bug with Android O devices, i must use a recent version of okhttp (at least 3.9.1) : https://github.com/square/okhttp/issues/3438

Because of some incompatibility between mobile-buy-sdk-android and okhttp 4.x (cf first comment of this issue describe by keepmovingljzy), i use okhttp 3.14.9.

But i encounter an issue reported many times by crashlytics with this version :
okhttp3.internal.cache.DiskLruCache.checkNotClosed
Fatal Exception: java.lang.IllegalStateException: cache is closed
       at okhttp3.internal.cache.DiskLruCache.checkNotClosed(DiskLruCache.java:645)
       at okhttp3.internal.cache.DiskLruCache.remove(DiskLruCache.java:607)
       at com.shopify.buy3.internal.cache.DiskLruCacheStore.remove(DiskLruCacheStore.kt:99)
       at com.shopify.buy3.internal.cache.HttpCache.removeQuietly(HttpCache.kt:72)
       at com.shopify.buy3.internal.GraphHttpResultCallback.purge(RealGraphCall.kt:337)
       at com.shopify.buy3.internal.GraphHttpResultCallback.onResponse(RealGraphCall.kt:321)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

I cannot use solution proposed by PiotrWpl and TimoPtr to implement ResponseCacheStore because of ResponseCacheStore is internal.
I prefere to not modify lib mobile-buy-sdk-android.


Coult it be possible to Shopify to fix this by used the last version of okhttp (or at least okhttp 4.x) ?
